/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tesp3;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class A4 extends javax.swing.JFrame {

    String a, NIK, Nama, Tempat, H, B, T, JK, Almt, RT, RW, Kel, Desa, Kec, Agama, ST, P, KW, BH;
    public A4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Tampil = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtNIK = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtTLahir = new javax.swing.JTextField();
        CmbH = new javax.swing.JComboBox();
        CmbB = new javax.swing.JComboBox();
        CmbT = new javax.swing.JComboBox();
        RdL = new javax.swing.JRadioButton();
        RdP = new javax.swing.JRadioButton();
        TxtAlamat = new javax.swing.JTextField();
        TxtRT = new javax.swing.JTextField();
        TxtRW = new javax.swing.JTextField();
        TxtKel = new javax.swing.JTextField();
        TxtDesa = new javax.swing.JTextField();
        TxtKec = new javax.swing.JTextField();
        CmbAgama = new javax.swing.JComboBox();
        RdM = new javax.swing.JRadioButton();
        RdBM = new javax.swing.JRadioButton();
        CmbP = new javax.swing.JComboBox();
        RdI = new javax.swing.JRadioButton();
        RdA = new javax.swing.JRadioButton();
        TxtBh = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane2.setViewportView(Area);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TampilLayout = new javax.swing.GroupLayout(Tampil.getContentPane());
        Tampil.getContentPane().setLayout(TampilLayout);
        TampilLayout.setHorizontalGroup(
            TampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TampilLayout.setVerticalGroup(
            TampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KTP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tempat/Tgl Lahir");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RT/RW");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kel/Desa");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kecamatan");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Agama");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status Perkawainan");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pekerjaan");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kewarganegaraan");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Berlaku Hingga");

        TxtNIK.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtNIK.setToolTipText("");

        TxtNama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TxtTLahir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        CmbH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbHActionPerformed(evt);
            }
        });

        CmbB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        CmbB.setToolTipText("");

        CmbT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));
        CmbT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(RdL);
        RdL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdL.setText("Laki-laki");
        RdL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdLActionPerformed(evt);
            }
        });

        buttonGroup1.add(RdP);
        RdP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdP.setText("Perempuan");

        TxtAlamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtAlamat.setToolTipText("");

        TxtRT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TxtRW.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TxtKel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TxtDesa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        TxtKec.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtKec.setToolTipText("");

        CmbAgama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Islam", "Kristen", "Katolik", "Hindu", "Buddha" }));
        CmbAgama.setToolTipText("");

        buttonGroup2.add(RdM);
        RdM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdM.setText("Menikah");
        RdM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdMActionPerformed(evt);
            }
        });

        buttonGroup2.add(RdBM);
        RdBM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdBM.setText("Belum Menikah");
        RdBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBMActionPerformed(evt);
            }
        });

        CmbP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CmbP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "PNS", "Pegawai Swasta", "Wirausaha" }));
        CmbP.setToolTipText("");

        buttonGroup3.add(RdI);
        RdI.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdI.setText("WNI");
        RdI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdIActionPerformed(evt);
            }
        });

        buttonGroup3.add(RdA);
        RdA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RdA.setText("WNA");
        RdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdAActionPerformed(evt);
            }
        });

        TxtBh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TxtBh.setText("Seumur Hidup");
        TxtBh.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Reset");

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Exit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)))
                                .addComponent(jLabel10))
                            .addGap(32, 32, 32))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(29, 33, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAlamat)
                            .addComponent(TxtKec)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtNama)
                                        .addComponent(TxtNIK)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TxtTLahir)
                                                .addComponent(RdL, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(CmbH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CmbB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(CmbT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(RdP, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TxtRT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtRW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TxtKel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtDesa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RdM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(RdBM))
                                    .addComponent(CmbP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RdI, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(RdA, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(TxtBh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtTLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RdL)
                        .addComponent(RdP)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CmbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdM)
                    .addComponent(RdBM)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CmbP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RdI)
                    .addComponent(RdA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtBh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(7, 7, 7)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdLActionPerformed

    private void RdMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdMActionPerformed

    private void RdBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBMActionPerformed

    private void RdIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdIActionPerformed

    private void RdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdAActionPerformed

    private void CmbHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbHActionPerformed
        a = CmbB.getSelectedItem().toString();      
        DefaultComboBoxModel modelcombo11 = new DefaultComboBoxModel();
        
        modelcombo11.addElement("1");
        modelcombo11.addElement("2");
        modelcombo11.addElement("3");
        modelcombo11.addElement("4");
        modelcombo11.addElement("5");
        modelcombo11.addElement("6");
        modelcombo11.addElement("7");
        modelcombo11.addElement("8");
        modelcombo11.addElement("9");
        modelcombo11.addElement("10");
        modelcombo11.addElement("11");
        modelcombo11.addElement("12");
        modelcombo11.addElement("13");
        modelcombo11.addElement("14");
        modelcombo11.addElement("15");
        modelcombo11.addElement("16");
        modelcombo11.addElement("17");
        modelcombo11.addElement("18");
        modelcombo11.addElement("19");
        modelcombo11.addElement("20");
        modelcombo11.addElement("21");
        modelcombo11.addElement("22");
        modelcombo11.addElement("23");
        modelcombo11.addElement("24");
        modelcombo11.addElement("25");
        modelcombo11.addElement("26");
        modelcombo11.addElement("27");
        modelcombo11.addElement("28");
        modelcombo11.addElement("29");
        modelcombo11.addElement("30");
        modelcombo11.addElement("31");
        
        if(a.equals("Januari")||a.equals("Maret")||a.equals("Mei")||a.equals("Juli")||a.equals("Agustus")||a.equals("Oktober")||a.equals("Desember"))
        {
            CmbH.setModel(modelcombo11);
        }
        
        DefaultComboBoxModel modelcombo12 = new DefaultComboBoxModel();
        
        modelcombo12.addElement("1");
        modelcombo12.addElement("2");
        modelcombo12.addElement("3");
        modelcombo12.addElement("4");
        modelcombo12.addElement("5");
        modelcombo12.addElement("6");
        modelcombo12.addElement("7");
        modelcombo12.addElement("8");
        modelcombo12.addElement("9");
        modelcombo12.addElement("10");
        modelcombo12.addElement("11");
        modelcombo12.addElement("12");
        modelcombo12.addElement("13");
        modelcombo12.addElement("14");
        modelcombo12.addElement("15");
        modelcombo12.addElement("16");
        modelcombo12.addElement("17");
        modelcombo12.addElement("18");
        modelcombo12.addElement("19");
        modelcombo12.addElement("20");
        modelcombo12.addElement("21");
        modelcombo12.addElement("22");
        modelcombo12.addElement("23");
        modelcombo12.addElement("24");
        modelcombo12.addElement("25");
        modelcombo12.addElement("26");
        modelcombo12.addElement("27");
        modelcombo12.addElement("28");
        modelcombo12.addElement("29");
        modelcombo12.addElement("30");
        
        if (a.equals("April")||a.equals("Juni")||a.equals("September")||a.equals("November"))
        {
            CmbH.setModel(modelcombo12);
        }
        
        DefaultComboBoxModel modelcombo13 = new DefaultComboBoxModel();
        modelcombo13.addElement("1");
        modelcombo13.addElement("2");
        modelcombo13.addElement("3");
        modelcombo13.addElement("4");
        modelcombo13.addElement("5");
        modelcombo13.addElement("6");
        modelcombo13.addElement("7");
        modelcombo13.addElement("8");
        modelcombo13.addElement("9");
        modelcombo13.addElement("10");
        modelcombo13.addElement("11");
        modelcombo13.addElement("12");
        modelcombo13.addElement("13");
        modelcombo13.addElement("14");
        modelcombo13.addElement("15");
        modelcombo13.addElement("16");
        modelcombo13.addElement("17");
        modelcombo13.addElement("18");
        modelcombo13.addElement("19");
        modelcombo13.addElement("20");
        modelcombo13.addElement("21");
        modelcombo13.addElement("22");
        modelcombo13.addElement("23");
        modelcombo13.addElement("24");
        modelcombo13.addElement("25");
        modelcombo13.addElement("26");
        modelcombo13.addElement("27");
        modelcombo13.addElement("28");
        
        if(a.equals("Februari"))
        {
            CmbH.setModel(modelcombo13);
        }
        
        
    }//GEN-LAST:event_CmbHActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        a = CmbB.getSelectedItem().toString();      
        DefaultComboBoxModel modelcombo11 = new DefaultComboBoxModel();
        
        modelcombo11.addElement("1");
        modelcombo11.addElement("2");
        modelcombo11.addElement("3");
        modelcombo11.addElement("4");
        modelcombo11.addElement("5");
        modelcombo11.addElement("6");
        modelcombo11.addElement("7");
        modelcombo11.addElement("8");
        modelcombo11.addElement("9");
        modelcombo11.addElement("10");
        modelcombo11.addElement("11");
        modelcombo11.addElement("12");
        modelcombo11.addElement("13");
        modelcombo11.addElement("14");
        modelcombo11.addElement("15");
        modelcombo11.addElement("16");
        modelcombo11.addElement("17");
        modelcombo11.addElement("18");
        modelcombo11.addElement("19");
        modelcombo11.addElement("20");
        modelcombo11.addElement("21");
        modelcombo11.addElement("22");
        modelcombo11.addElement("23");
        modelcombo11.addElement("24");
        modelcombo11.addElement("25");
        modelcombo11.addElement("26");
        modelcombo11.addElement("27");
        modelcombo11.addElement("28");
        modelcombo11.addElement("29");
        modelcombo11.addElement("30");
        modelcombo11.addElement("31");
     
        CmbH.setModel(modelcombo11);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NIK = TxtNIK.getText();
        Nama = TxtNama.getText();
        Tempat = TxtTLahir.getText();
        H = CmbH.getSelectedItem().toString();
        B = CmbB.getSelectedItem().toString();
        T = CmbT.getSelectedItem().toString();
        
        if(RdL.isSelected())
        {
            JK = RdL.getText();
        }
        else if (RdP.isSelected())
        {
           JK = RdP.getText();
        }
        
        Almt = TxtAlamat.getText();
        RT = TxtRT.getText();
        RW = TxtRW.getText();
        Kel = TxtKel.getText();
        Desa = TxtDesa.getText();
        Kec = TxtKec.getText();
        Agama = CmbAgama.getSelectedItem().toString();
        
        if(RdM.isSelected())
        {
            ST = RdM.getText();
        }
        else if (RdBM.isSelected())
        {
           ST = RdBM.getText();
        }
        
        P = CmbP.getSelectedItem().toString();
        
        if(RdI.isSelected())
        {
            KW = RdI.getText();
        }
        else if (RdA.isSelected())
        {
           KW = RdA.getText();
        }
        
        BH = TxtBh.getText();
        
        JOptionPane.showMessageDialog(null, "Data Tersimpan");
        
        
        Tampil.setVisible(true);
        Area.setText
        (
                "NIK : "+NIK+
                "\nNama"+Nama+
                "\nTempat/Tgl Lahir : "+Tempat+" / "+H+" "+B+" "+T+" "+
                "\nJenis Kelamin : "+JK+
                "\nAlamat"+Almt+
                "\nRT/RW : "+RT+" / "+RW+
                "\nKel/Desa : "+Kel+" / "+Desa+
                "\nKecamatan : "+Kec+
                "\nAgama : "+Agama+
                "\nStatus Perkawainan : "+ST+
                "\nKewarganegaraan : "+KW+
                "\nBerlaku Hingga : "+BH        
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JComboBox CmbAgama;
    private javax.swing.JComboBox CmbB;
    private javax.swing.JComboBox CmbH;
    private javax.swing.JComboBox CmbP;
    private javax.swing.JComboBox CmbT;
    private javax.swing.JRadioButton RdA;
    private javax.swing.JRadioButton RdBM;
    private javax.swing.JRadioButton RdI;
    private javax.swing.JRadioButton RdL;
    private javax.swing.JRadioButton RdM;
    private javax.swing.JRadioButton RdP;
    private javax.swing.JFrame Tampil;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtBh;
    private javax.swing.JTextField TxtDesa;
    private javax.swing.JTextField TxtKec;
    private javax.swing.JTextField TxtKel;
    private javax.swing.JTextField TxtNIK;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtRT;
    private javax.swing.JTextField TxtRW;
    private javax.swing.JTextField TxtTLahir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
